[package]
name = "rust_pdbloader"
version = "0.1.0"
authors = ["yamule <1697130+yamule@users.noreply.github.com>"]
edition = "2018"

[dependencies]
lazy_static="1.4.0"
regex="1.3.1"
rand="0.7.3"
rand_distr="0.2.2"
roxmltree="0.14.0"
flate2 = "1.0"
chrono="0.4"
#ocl = "0.19"
#ocl-core = "0.11.2"
